In [1]:
#1.Write a function to compute 5/0 and use try/except to catch the exceptions. 

# Divide by zero
try:
    x = 5 / 0
except:
    print("Error dividing by zero")

Error dividing by zero


In [3]:
#2.  Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
 
#Hint: Subject,Verb and Object should be declared in the program as shown below. 
 
#subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"] 

#solution


subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]
sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sentence in sentence_list:
 print (sentence)



Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [8]:
#TASK 2 --1.
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)
array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])
np.column_stack([x**(N-1-i) for i in range(N)])
array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])
x = np.array([1, 2, 3, 5])
np.vander(x)
array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])
np.vander(x, increasing=True)
array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

NameError: name 'array' is not defined